// To add more reward types, simply add them to this array.
// The form dropdowns will update automatically.
export const REWARD_TYPES = [
    "DIAMOND",
    "GOLD",
    "STAR",
    "MONSTER",
    "RESET_STONE",
    "ARTIFACT",
    "GOLD_LEVEL",
    "NORMAL_FUSION_BOTTLE",
    "RARE_FUSION_BOTTLE",
    "NORMAL_EGG",
    "RARE_EGG",
    "ELEMENTAL_EGG",
    "LEGEND_EGG",
    "STAR_FUSION_EVENT",
    "DICE",
    "REMOVE_ADS",
    "GALAXY_EGG",
    "STAR_GALAXY_EVENT",
    "CHRISTMAS_TICKET",
    "CHRISTMAS_BELL",
    "MUTANT_BOTTLE",
    "HAMMER",
    "CHRISTMAS_7Days_X2",
    "CHRISTMAS_7Days_X4",
    "VIP_PACK",
    "CHALLENGE_TICKET",
    "FISH_BAIT",
    "AVIATOR_STONE",
    "CHALLENGE_STONE",
    "PURCHASE_PACK",
    "PVP_TICKET",
    "PVP_RANK_POINT",
    "RACE_TICKET_RANDOM",
    "RACE_TICKET_1_STAR",
    "RACE_TICKET_2_STAR",
    "RACE_TICKET_3_STAR",
    "RACE_TICKET_4_STAR",
    "RACE_TICKET_5_STAR",
    "RACE_TICKET_6_STAR",
    "DIAMOND_PACK_EVERYDAY",
    "UNLOCK_ALL_FARMS",
    "SPEED_UP_COMBAT",
    "TIME_SKIP_FREE",
    "UNLIMITED_AUTO_FUSION",
    "EXPLORE_SKIP_FREE",
    "AVATAR_INFO_PLAYER",
    "FRAME_AVATAR_INFO_PLAYER",
    "LUNARIS_BLOOM",
    "DIVINE_SPIRIT",
    "JIGSAW_SUPREME_FRAG",
    "JIGSAW_DIVINE_FRAG",
    "JIGSAW_LEGENG_FRAG",
    "THUNDER_EGG",
    "SOLO_BATTLE_TICKET",
] as const;

export const ARTIFACT_RARITIES = [
    "None",
    "NORMAL",
    "UNCOMMON",
    "RARE",
    "EPIC",
    "LEGEND",
    "DIVINE",
    "SUPREME",
] as const;

export const ARTIFACT_PIECE_TYPES = [
    "None",
    "WolfClaw", "WolfFang", "WolfEye", "Wolf_FullSet",
    "LionClaw", "LionHeart", "LionTail", "Lion_FullSet",
    "WildBoarTusk", "WildBoarFeet", "WildBoarTail", "WildBoar_FullSet",
    "BeeWing", "BeeTail", "BeeEye", "Bee_FullSet",
    "SharkFin", "SharkJaw", "SharkTail", "Shark_FullSet",
    "UnicornHorn", "UnicornClaw", "UnicornTail", "Unicorn_FullSet",
    "DragonScale", "DragonHorn", "DragonClaw", "Dragon_FullSet",
] as const;

type ArtifactPieceType = typeof ARTIFACT_PIECE_TYPES[number];

const PIECE_TYPE_TO_CLASS_CHAR: Record<ArtifactPieceType, string> = {
    None: "A",
    WolfClaw: "A", WolfFang: "A", WolfEye: "A", Wolf_FullSet: "A",
    LionClaw: "B", LionHeart: "B", LionTail: "B", Lion_FullSet: "B",
    WildBoarTusk: "C", WildBoarFeet: "C", WildBoarTail: "C", WildBoar_FullSet: "C",
    BeeWing: "D", BeeTail: "D", BeeEye: "D", Bee_FullSet: "D",
    SharkFin: "E", SharkJaw: "E", SharkTail: "E", Shark_FullSet: "E",
    UnicornHorn: "F", UnicornClaw: "F", UnicornTail: "F", Unicorn_FullSet: "F",
    DragonScale: "G", DragonHorn: "G", DragonClaw: "G", Dragon_FullSet: "G",
};

export function getClassCharForPieceType(pieceType: ArtifactPieceType): string {
    return PIECE_TYPE_TO_CLASS_CHAR[pieceType] || "A";
}

export const IAP_PACKS = [
    "pack250",
    "pack500",
    "pack1250",
    "pack2500",
    "pack5000",
    "vippack1",
    "vippack2",
    "vippack3",
    "legendegginshop",
    "legendeggingift",
    "adspasspack",
    "battlepass",
    "mutantpass",
    "breederpack",
    "researcherpack",
    "collectorpack",
    "seekerpack",
    "zoologistpack",
    "bankerpack",
    "butcherpack",
    "iap_legend_egg_sale_1",
    "iap_legend_egg_sale_3",
    "iap_legend_egg_sale_5",
    "iap_diamond_sale_5000",
    "iap_normal_egg_sale_100",
    "iap_reset_stone_sale_10",
    "iap_dice_sale_20",
    "iap_rare_fusion_potion_5",
    "iap_rare_fusion_potion_10",
    "iap_rare_fusion_potion_20",
    "fusionevent_01_pack02",
    "fusionevent_01_pack03",
    "fusionevent_01_pack04",
    "fusionevent_01_pack05",
    "fusionevent_01_pack06",
    "galaxyevent_pack06",
    "premiumshop_starterpack",
    "premiumshop_vippack",
    "premiumshop_vippack_sub",
    "premiumshop_toolpack",
    "premiumshop_eggpack",
    "premiumshop_alotegg",
    "premiumshop_legendeggsale",
    "premiumshop_elementalegg",
    "christmasevent_pack1",
    "christmasevent_pack2",
    "christmasevent_pack3",
    "christmasevent_pack4",
    "christmasevent_pack5",
    "aviator_shop_item_1",
    "aviator_shop_item_2",
    "aviator_shop_item_3",
    "aviator_shop_item_4",
    "aviator_shop_item_5",
    "aviator_shop_item_6",
    "challenge_pass_pack",
    "refresh_explorer_pack",
    "race_event_wind_pass_pack",
    "solobattle_ticket_pass_pack",
    "mazeruins_move_pack"
] as const;
